### ISSUE TITLE
Rails 7 compatibility

### ISSUE THREAD

**Issue by swistak35** [t12nslookup/activerecord-advantage-adapter#2]
Hey,
I'm wondering if you are interested in keeping ActiveRecord 7 compatibility.

To make the gem work in my current project I'm using following monkeypatch:

```
module ActiveRecord
  module ConnectionAdapters
    class AdvantageAdapter
      # Monkeypatched: Added **options to method definition
      def exec_query(sql, name = "SQL", _binds = [], **_options)
        cols, record = execute(sql, name)
        ActiveRecord::Result.new(cols, record)
      end

      # Monkeypatched: Added **options to method definition and passed into exec_query
      def select(sql, name = nil, binds = [], **options) #:nodoc:
        if Rails::VERSION::MAJOR >= 4
          exec_query(sql, name, binds, **options)
        else
          exec_query(sql, name, binds, **options).to_hash
        end
      end
    end
  end
end
```

Note that I only use in specs SELECT queries, no modifications, so all other types of SQL queries are not covered by this and some additional changes may be needed.

**Comment by t12nslookup** [comment]
Absolutely looking to keep this compatible. I thought I'd run against rails 7, but I may have only run up till 6.1.

I'll look to make time to convert this to a versioned patch, unless you have the time to do it and submit the update?

**Comment by t12nslookup** [comment]
published an updated version, with your changes (and a tweak to "count" to stop failures when multiple columns are "select"ed, and no column is specified to "count")

**Comment by swistak35** [comment]
I've found one more incompatibility -- when the column is boolean, on rails 7 it started to return 0/1 (Integer) instead of false/true

**Comment by t12nslookup** [comment]
> I've found one more incompatibility -- when the column is boolean, on rails 7 it started to return 0/1 (Integer) instead of false/true

Ta. I don't have any booleans in my test db ... I'll create some so I can do testing. Can you raise it as a new issue?

**Comment by swistak35** [comment]
Done #3
