### ISSUE TITLE
Boolean type incompatibility with ActiveRecord 7

### ISSUE THREAD

**Issue by swistak35** [t12nslookup/activerecord-advantage-adapter#3]
I've found one more incompatibility -- when the column is boolean, on rails 7 it started to return 0/1 (Integer) instead of false/true.

**Comment by t12nslookup** [comment]
okay, I now know that rails 7 doesn't appear to call `initialize_type_map` by itself any more, and because I was lazy and used `super` from that function to call the `abstract_adapter.rb` function of the same name, I'm going to have to play with the hardcoding the `type_map` ... should never be a problem, as this database isn't going to change, but is a thing ...

**Comment by t12nslookup** [comment]
I've uploaded a version to git that appears to work for all of my tests (rails 4 through to 7).

If you get the chance can you try to use this and see if I'm missing any of your database types that you might need?

**Comment by swistak35** [comment]
Taking code from master I indeed no longer issue with booleans, though I do have with some columns which were previously converted into BigDecimal. What is interesting, the BigDecimal part works fine on 0.1.7 so there must have been something on master which broke it

**Comment by t12nslookup** [comment]
Yeah, that was my suspicions ... By removing `super` I completely broke that bit of code ... I guess that's my fault for being lazy in the first place, around the time I put in rails 4 compatibility.

I'll create some more different record types in my test db, and check the before and after for compatibility ... I've got a compete list of types, so it'll just take some patience.

**Comment by t12nslookup** [comment]
okay, git pushed to "main", which should fix the "doubles" as floats:
```
pp ActiveRecord::Base.connection.columns('WORKSHEET').map{|x| [x.name, x.type, x.sql_type]}
[["ROWID", :string, "CHAR"],
 ["wkid", :integer, "AUTOINC"],
 ["name", :string, "VARCHAR"],
 ["expired", :boolean, "LOGICAL"],
 ["when_created", :datetime, "TIMESTAMP"],
 ["who_created", :string, "VARCHAR"],
 ["column1", :float, "DOUBLE"],
 ["column2", :float, "CURDOUBLE"],
 ["column3", :integer, "LONGINT"],
 ["column4", nil, "MONEY"],
 ["column5", :time, "MODTIME"],
 ["column6", :datetime, "TIMESTAMP"],
 ["column7", :integer, "SHORT"],
 ["column8", :binary, "RAW"]]
```
not quite sure why "Money" is unknown ... (it's pretending to be an `Integer` for load/save) ... but it all appears to be behaving for me.

If you get the chance can you check again and see if that's better?

**Comment by swistak35** [comment]
Hey, no, still that column doesn't work. I've added breakpoint to `lookup_cast_type_from_column` and for the `column` variable I got that:

```
=> #<ActiveRecord::ConnectionAdapters::AdvantageColumn:0x088191f8
 @collation=nil,
 @comment=nil,
 @default=nil,
 @default_function=nil,
 @name="AMOUNTEUR",
 @null=1,
 @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SqlTypeMetadata:0x0881939c @limit=nil, @precision=nil, @scale=nil, @sql_type="NUMERIC", @type=nil>>
```

So I've looked into advantage's type map and I see that we do:

```
m.alias_type %r(numeric)i, "decimal"
```
But there is no "decimal" type in the first place defined.

So I've removed that alias and added just:

```
register_class m, %r(numeric)i, Type::Decimal
```

And that made it work. My guess is that after that, we need to also change the aliases (for example, money) from `m.alias_type %r(money)i,    "decimal"` to `m.alias_type %r(money)i,    "numeric"` ? (I don't have tests to verify that)

**Comment by t12nslookup** [comment]
Ta. Good catch.

I'll look at defining `decimal` shortly, and hopefully that'll be the last fix, as everything should just update.

**Comment by t12nslookup** [comment]
godamnit!

I have suspicions that the `INT2FIX` function in `ads_get_column` is causing an issue with any decimals (`advantage` gem) ... all my `MONEY` is returning as an Integer:
```
2.7.3 :004 > xxx=Worksheet.first
 => #<Worksheet ROWID: "CPdLexCgwDlEAAAAAB", wkid: 1, name: "First", expired: nil, when_created: "2023-06-20 13:09...
2.7.3 :005 > xxx.column4
 => 0.27e2
2.7.3 :006 > xxx.column4.class
 => BigDecimal
2.7.3 :007 > xxx.column4.to_s
 => "27.0"
2.7.3 :008 > xxx.column4 = 27.72
 => 27.72
2.7.3 :009 > xxx.column4.class
 => BigDecimal
2.7.3 :010 > xxx.column4.to_s
 => "27.72"
2.7.3 :011 > xxx.save
  update (25.0ms)  UPDATE "WORKSHEET" SET "column4" = 27.72 WHERE "WORKSHEET"."ROWID" = 'CPdLexCgwDlEAAAAAB'
 => true
2.7.3 :012 > xxx=Worksheet.first
 => #<Worksheet ROWID: "CPdLexCgwDlEAAAAAB", wkid: 1, name: "First", expired: nil, when_created: "2023-06-20 13:09...
2.7.3 :013 > xxx.column4
 => 0.28e2
2.7.3 :014 > xxx.column4.to_s
 => "28.0"
```
(separate DBeaver access shows the value stored in the database as `27.72`) so it has to be the `advantage` gem that is causing this problem ... I don't use money for any of my items, so it hasn't been causing me a problem, but I suspect that anything that should be a `decimal` will suffer from the same problem.

Jon

**Comment by t12nslookup** [comment]
the decimal places appear to be a weakness of the `advantage` gem, so the changes looks good.

I've pushed the changes, bumped the version and will look at the `advantage` adapter when I get the chance to see if I can get real decimals to behave.
